### ISSUE TITLE
hellow

### ISSUE THREAD

**Issue by rodri2200** [Pymmdrza/TRONPRO#2]
![tron](https://github.com/Pymmdrza/TRONPRO/assets/163687301/ea02145d-f7cb-4ac5-b4f5-c07fb905bd23)

**Comment by Pymmdrza** [comment]
> ![tron](https://private-user-images.githubusercontent.com/163687301/319891737-ea02145d-f7cb-4ac5-b4f5-c07fb905bd23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzE3ODcsIm5iZiI6MTcxMjMzMTQ4NywicGF0aCI6Ii8xNjM2ODczMDEvMzE5ODkxNzM3LWVhMDIxNDVkLWY3Y2ItNGFjNS1iNGY1LWMwN2ZiOTA1YmQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNTM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjg4YzA2MmU4ZTcxMWUyM2E2ZWMzYzAxMDc3NzYzOWYxNGYwYTk4NDBhZDE2ZDJiMGM3YTRlNWNmY2MwZTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V4zME39SNyq3_sn5n-CvJd5MyHxoWfh3_1liVoldgzg)

`pip install pycryptodome==3.4.3`

**Comment by rodri2200** [comment]
The same thing comes out when you execute that pip

**Comment by Pymmdrza** [comment]
first install package's : 
```bash
pip install --upgrade cryptofuzz
pip install --upgrade colorthon
```

save and use this source on python file : 
```python
import random
from colorthon import Colors as Fore
import base58, requests
from cryptofuzz import Tron

trx = Tron()
def seek():
    count = 0
    while True:
        raw = bytes(random.sample(range(0, 256), 32))
        privatekey = raw.hex()
        Wallet = trx.hex_addr(privatekey)
        HexAdd = base58.b58encode_check(Wallet.encode()).hex()

        block = requests.get("https://apilist.tronscan.org/api/account?address=" +Wallet)
        res = block.json()
        txid = dict(res)["totalTransactionCount"]
        count += 1
        print(f"[{str(count)}] Wallet: {Fore.GREY}{Wallet} {Fore.RESET} |Txs: {Fore.RED}{str(txid)}{Fore.RESET} | PVK: {Fore.YELLOW}{str(privatekey)}{Fore.RESET}")


        if int(txid) > 0:
            print("======================================================")
            print("||Address Wallet = " + Wallet)
            print("||Private Key = " + privatekey)
            print("||Hex Address = " + HexAdd)
            print("=======================================================")
            f = open(u"Winner.txt", "a")
            f.write("\n====================================================")
            f.write("Wallet Winner Address = " + Wallet)
            f.write("Private Key = " + privatekey)
            f.write("Hex Address = " + HexAdd)
            f.write("=========================================================\n")
            continue
seek()
```

**Comment by Pymmdrza** [comment]
![rec06-04-2024 20-34-04](https://github.com/Pymmdrza/TRONPRO/assets/95309780/62ad809a-2e78-4fc7-ba90-558ccd9483a1)


> first install package's :
> 
> ```shell
> pip install --upgrade cryptofuzz
> pip install --upgrade colorthon
> ```
> 
> save and use this source on python file :
> 
> ```python
> import random
> from colorthon import Colors as Fore
> import base58, requests
> from cryptofuzz import Tron
> 
> trx = Tron()
> def seek():
>     count = 0
>     while True:
>         raw = bytes(random.sample(range(0, 256), 32))
>         privatekey = raw.hex()
>         Wallet = trx.hex_addr(privatekey)
>         HexAdd = base58.b58encode_check(Wallet.encode()).hex()
> 
>         block = requests.get("https://apilist.tronscan.org/api/account?address=" +Wallet)
>         res = block.json()
>         txid = dict(res)["totalTransactionCount"]
>         count += 1
>         print(f"[{str(count)}] Wallet: {Fore.GREY}{Wallet} {Fore.RESET} |Txs: {Fore.RED}{str(txid)}{Fore.RESET} | PVK: {Fore.YELLOW}{str(privatekey)}{Fore.RESET}")
> 
> 
>         if int(txid) > 0:
>             print("======================================================")
>             print("||Address Wallet = " + Wallet)
>             print("||Private Key = " + privatekey)
>             print("||Hex Address = " + HexAdd)
>             print("=======================================================")
>             f = open(u"Winner.txt", "a")
>             f.write("\n====================================================")
>             f.write("Wallet Winner Address = " + Wallet)
>             f.write("Private Key = " + privatekey)
>             f.write("Hex Address = " + HexAdd)
>             f.write("=========================================================\n")
>             continue
> seek()
> ```
